### ISSUE TITLE
how use your version but with sayit of mysociety

### ISSUE THREAD

**Issue by johnfelipe** [KohoVolit/sayit.parldata.eu#9]
Hi, please tell me how use your version, but still using sayit of mysociety?
Is possible?

**Comment by girogiro** [comment]
It uses SayIt app of MySociety with some small modifications (in ordering of sections). Because of that it's part of the repository. It should be OK to remove the `/speeches` dir and use original SayIt app installed in your Python path. Most of the changes will still apply as they are on the Django project level (directory `/sayit_parldata_eu`) and not on the SayIt app level.

**Comment by johnfelipe** [comment]
you tell me in this case install in other path /sayit_parldata_eu?
This is my original sayit of mysociety and with python 2.x:

![sayir](https://cloud.githubusercontent.com/assets/428820/6953140/dfcabf68-d88c-11e4-9e4e-0f0aa5e6847f.png)

**Comment by girogiro** [comment]
I don't understand. You can use KohoVolit/sayit.parldata.eu project or MySociety/sayit.mysociety.org project. Not both.

Both of them utilize reusable app MySociety/SayIt, the first one uses a slightly modified app. But you can replace the modified app by the original one.

**Comment by johnfelipe** [comment]
i need install your app, but in localhost enviroment how do that?, what replace or edit for job complete?, tnks

**Comment by girogiro** [comment]
Just follow the installation instructions. There may be some minor differences you can overcome with Google.
